### ISSUE TITLE
Error occurred while parsing function triggers

### ISSUE THREAD

**Issue by rakhimian** [HathTech/shoppers#1]
/Users/air/AndroidStudioProjects/snabzenie/functions/index.js:1
import * as functions from 'firebase-functions'
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:15:15
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:53:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

**Comment by HathTech** [comment]
Hey, do 
cd functions; yarn install

**Comment by rakhimian** [comment]
> Hey, do
> cd functions; yarn install

Thank you! 
But I've Mac OS. So I tried by adding `brew install yarn`. But it's still getting error ..


Error: Error occurred while parsing your function triggers.

/Users/air/AndroidStudioProjects/snabzenie/functions/index.js:19
import * as functions from 'firebase-functions'
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:15:15
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:53:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

Having trouble? Try firebase deploy --help
Air-Rakhimyan:snabzenie air$ yarn -v
1.19.1
Air-Rakhimyan:snabzenie air$

**Comment by HathTech** [comment]
Hey, Follow the steps like this. 

- Go to the functions directory
- There you can install `yarn install `

If you are still facing this issue share a video of what you are doing to support@hathtech.com

**Comment by rakhimian** [comment]
Hi, look 

```
Air-Rakhimyan:functions air$ yarn install
yarn install v1.19.1
[1/5] 🔍  Validating package.json...
error functions@: The engine "node" is incompatible with this module. Expected version "8". Got "10.16.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Air-Rakhimyan:functions air$
```

**Comment by HathTech** [comment]
Use node version 8.

**Comment by rakhimian** [comment]
Here my package.json file

```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "dependencies": {
    "firebase-admin": "^8.6.0",
    "firebase-functions": "^3.3.0"
  },
  "devDependencies": {
    "firebase-functions-test": "^0.1.6"
  },
  "private": true
}
```
Node version

```
Air-Rakhimyan:~ air$ node -v
v10.16.3
```
So if it's not same please help me how I can install needed node version? Thanks!

**Comment by HathTech** [comment]
Hey have you purchased this product from  
https://1.envato.market/07QmM

If not do purchase it and join our gitlab repository for latest code. 

If yes share your invoice and gitlab email to support@hathtech.com
